---
# All hosts get the common role
- name: Common configuration
  hosts: all
  roles: [common]

# Hosts in the postgresql group get the postgresql role
- name: PostgreSQL configuration
  hosts: postgresql
  roles: [postgresql]

# Hosts in the web group get the nginx and lets-encrypt roles
- name: Web configuration
  hosts: web
  roles: [nginx, lets-encrypt]
