---
dependencies:
  - role: nginx
    vars:
      https: enabled
      ssl_certificate: /etc/letsencrypt/live/{{ hostname }}/fullchain.pem
      ssl_certificate_key: /etc/letsencrypt/live/{{ hostname }}/privkey.pem
