---
- name: Install certbot
  become: yes
  apt:
    name: certbot
    state: present
    cache_valid_time: 86400  # 1 day

- name: Obtain Let's Encrypt certificate
  become: yes
  command: /usr/bin/certbot certonly --standalone -d {{ hostname }} --rsa-key-size 4096 --email {{ letsencrypt_email }} --non-interactive --agree-tos --pre-hook "/bin/systemctl stop nginx" --post-hook "/bin/systemctl start nginx"
  args:
    creates: /etc/letsencrypt/live/{{ hostname }}/cert.pem

- name: Automatically renew certificate
  become: yes
  cron:
    name: Renew Let's Encrypt certificates
    special_time: daily
    job: /usr/bin/certbot renew --standalone --pre-hook "/bin/systemctl stop nginx" --post-hook "/bin/systemctl start nginx"
